server:
  host: "127.0.0.1"
  port: 8080
  workers: 4
  database:
    url: "sqlite://test.db"

rest_api:
  enabled: true
  prefix: "/api/v1"

logging:
  level: "info"
  targets:
    - type: "console"
      enabled: true

# Registry configuration for task discovery
registry:
  update_interval: 60
  concurrent_updates: 2
  retry_attempts: 3
  
  sources:
    # Local sample tasks
    - name: "sample-tasks"
      polling_interval: 30
      uri: "file://sample/js-tasks/tasks"
      config:
        watch_for_changes: true
        auto_reload: true
        include_patterns:
          - "*.js"
          - "*.yaml"
          - "*.json"
        recursive: true
        max_depth: 5

# MCP configuration for task development tools
mcp:
  enabled: true
  transport: "sse"
  server:
    host: "127.0.0.1"
    port: 8090
    enable_cors: true
  tools:
    enable_execution: true
    enable_logging: true
    enable_debugging: true
