[workspace]
members = [
    "ratchet-core",
    "ratchet-runtime",
    "ratchet-storage", 
    "ratchet-api",
    "ratchet-ipc",
    "ratchet-resilience",
    "ratchet-caching",
    "ratchet-plugins",
    "ratchet-mcp",      # New MCP implementation
    "ratchet-lib",      # Keep for now during migration
    "ratchet-cli", "ratchet-config", "ratchet-plugin",
]
resolver = "2"

# Workspace-level dependencies shared by all crates
[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.45", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
lazy_static = "1.4"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.10", features = ["v4", "serde"] }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "chrono", "uuid"] }
axum = "0.6"
reqwest = { version = "0.11", features = ["json", "stream"] }
url = "2.4"
async-trait = "0.1"
tokio-stream = "0.1"

# Workspace-level configuration for targets
[workspace.package]
version = "0.0.6"  # Common version for all crates
authors = ["Michiel Kalkman <michiel@nosuchtype.com>"]
edition = "2021"
rust-version = "1.75"
license = "MIT OR Apache-2.0"
repository = "https://github.com/michiel/ratchet-workspace"

# Speed up compilation in debug mode
[profile.dev]
opt-level = 0
debug = true
# Split debug information if possible (helps reduce binary size during development)
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256

# Optimize for release builds
[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 16

# Create a smaller, optimized build for distributing binaries
[profile.dist]
inherits = "release"
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true
