server:
  host: "127.0.0.1"
  port: 3080
  workers: 4
  database:
    url: "sqlite://ratchet_test.db"

rest_api:
  enabled: true
  prefix: "/api/v1"

logging:
  level: "debug"
  targets:
    - type: "console"
      enabled: true

scheduler:
  enabled: true