version: '3.8'

services:
  ratchet:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        BUILD_DATE: ${BUILD_DATE}
        VCS_REF: ${VCS_REF}
    ports:
      - "8080:8080"  # REST API
      - "8081:8081"  # GraphQL API
      - "8082:8082"  # MCP Server
    volumes:
      - ratchet_data:/app/data
      - ratchet_logs:/app/logs
      - ./config:/app/config:ro
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - RATCHET_DATA_DIR=/app/data
      - RATCHET_LOG_DIR=/app/logs
      - RATCHET_CONFIG_DIR=/app/config
    healthcheck:
      test: ["CMD", "ratchet", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  ratchet_data:
    driver: local
  ratchet_logs:
    driver: local