# Configuration for MCP Console Testing
server:
  host: "127.0.0.1"
  port: 8080
  workers: 2

rest_api:
  enabled: true
  prefix: "/api/v1"

graphql_api:
  enabled: true
  endpoint: "/graphql"

# MCP API with SSE transport (for console)
mcp_api:
  enabled: true
  transport: "sse"  # Simple SSE transport for console
  host: "127.0.0.1"
  port: 8080  # Same port as main server
  endpoint: "/mcp"
  max_sessions: 50
  session_timeout_minutes: 30
  max_events_per_session: 500

logging:
  level: "debug"
  targets:
    - type: "console"
      enabled: true

database:
  url: "sqlite://ratchet-mcp-console.db"
  enable_migrations: true

registry:
  # Use embedded registry

heartbeat:
  enabled: true
  interval_seconds: 30
  max_failures: 3