# Minimal configuration for testing heartbeat stdout output
server:
  database:
    url: "sqlite::memory:"  # Use in-memory database for testing

heartbeat:
  enabled: true
  cron_schedule: "* * * * *"  # Every minute for faster testing
  output_destinations: ["stdio"]

# Enable info logging to see heartbeat messages
logging:
  level: info
  format: text
  targets:
    - type: console
      level: info