# Ratchet Configuration Example
# This file demonstrates the main configuration options with accurate defaults
# All sections are optional - the system will use sensible defaults if omitted

# Task execution configuration
execution:
  max_execution_duration: 300  # Default: 300 seconds (5 minutes)
  validate_schemas: true       # Default: true
  max_concurrent_tasks: 10     # Default: 10
  timeout_grace_period: 5      # Default: 5 seconds
  
  # JavaScript variable names for HTTP fetch operations
  fetch_variables:
    url_var: "__fetch_url"           # Default: "__fetch_url"
    params_var: "__fetch_params"     # Default: "__fetch_params"
    body_var: "__fetch_body"         # Default: "__fetch_body"
    result_var: "__http_result"      # Default: "__http_result"
    temp_result_var: "__temp_result" # Default: "__temp_result"

# HTTP client configuration
http:
  timeout: 30                    # Default: 30 seconds
  max_redirects: 10              # Default: 10
  user_agent: "Ratchet/1.0"     # Default: "Ratchet/1.0"
  verify_ssl: true               # Default: true
  
  # Connection pool settings
  connection_pool:
    max_idle_per_host: 10        # Default: 10
    idle_timeout: 90             # Default: 90 seconds
    connection_timeout: 10       # Default: 10 seconds

# Caching configuration
cache:
  enabled: true                  # Default: true
  
  # Task content cache settings
  task_cache:
    cache_type: "lru"            # Default: "lru"
    task_content_cache_size: 100 # Default: 100
    memory_limit_bytes: 67108864 # Default: 64MB
    ttl: 3600                    # Default: 3600 seconds (1 hour)
  
  # HTTP response cache settings
  http_cache:
    enabled: true                # Default: true
    max_size_bytes: 10485760     # Default: 10MB
    default_ttl: 300             # Default: 300 seconds (5 minutes)
    respect_cache_control: true  # Default: true
  
  # Result cache settings
  result_cache:
    enabled: true                # Default: true
    cache_only_success: true     # Default: true
    max_entries: 1000           # Default: 1000
    ttl: 1800                   # Default: 1800 seconds (30 minutes)

# Logging configuration
logging:
  level: info                    # Default: info (trace, debug, info, warn, error)
  format: text                   # Default: text (text, json)
  include_location: false        # Default: false
  structured: true               # Default: true
  
  # Log targets (where logs are written)
  targets:
    - type: console              # Output to console
      level: info                # Optional: override global level

# Output destinations configuration
output:
  max_concurrent_deliveries: 10  # Default: 10
  default_timeout: 30            # Default: 30 seconds
  validate_on_startup: true      # Default: true
  
  # Default retry policy for failed deliveries
  default_retry_policy:
    max_attempts: 3              # Default: 3
    initial_delay_ms: 1000       # Default: 1000ms (1 second)
    max_delay_ms: 30000         # Default: 30000ms (30 seconds)
    backoff_multiplier: 2.0      # Default: 2.0

# Server configuration (optional)
server:
  bind_address: "127.0.0.1"      # Default: "127.0.0.1"
  port: 8080                     # Default: 8080
  
  # Database configuration
  database:
    url: "sqlite:./ratchet.db"   # Default: "sqlite::memory:"
    max_connections: 10          # Default: 10
    min_connections: 1           # Default: 1
    connection_timeout: 30       # Default: 30 seconds
    idle_timeout: 600           # Default: 600 seconds (10 minutes)
    max_lifetime: 3600          # Default: 3600 seconds (1 hour)
  
  # CORS configuration
  cors:
    allowed_origins: ["*"]       # Default: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE"] # Default
    allowed_headers: ["Content-Type", "Authorization", "X-Requested-With"] # Default
    allow_credentials: false     # Default: false
    max_age: 3600               # Default: 3600 seconds
  
  # Rate limiting configuration
  rate_limit:
    enabled: true                # Default: true
    requests_per_minute: 60      # Default: 60
    burst_size: 10              # Default: 10
    time_window: 60             # Default: 60 seconds

# Task registry configuration (optional)
registry:
  sources:
    - name: "local-tasks"              # Source name
      uri: "file://./sample/js-tasks"  # Local filesystem path
      polling_interval: 30             # Required field for polling interval in seconds
      config:
        watch_for_changes: true        # Enable file watching
        auto_reload: false             # Auto-reload on changes
  
  default_polling_interval: 300        # Default: 300 seconds (5 minutes)
  
  # Registry cache settings
  cache:
    enabled: true                      # Default: true
    ttl: 3600                         # Default: 3600 seconds (1 hour)
    max_entries: 1000                 # Default: 1000

# Environment variables that can override config values:
#
# RATCHET_HTTP_TIMEOUT=60
# RATCHET_CACHE_ENABLED=true
# RATCHET_LOG_LEVEL=debug
# RATCHET_MAX_EXECUTION_DURATION=600
# RATCHET_DATABASE_URL=sqlite://./ratchet.db
# RATCHET_SERVER_PORT=3000
# RATCHET_BIND_ADDRESS=0.0.0.0
#
# For logging, use standard Rust environment variables:
# RUST_LOG=debug                    # Set global log level
# RUST_LOG=ratchet=debug           # Set log level for ratchet modules only