# Ratchet MCP Minimal Configuration
# This is a minimal configuration for basic MCP server functionality
# Only essential settings are included - all others use defaults

# Basic execution settings (optional - defaults shown)
execution:
  max_execution_duration: 300  # Default: 300 seconds
  validate_schemas: true       # Default: true

# HTTP settings (optional - defaults shown)
http:
  timeout: 30          # Default: 30 seconds
  verify_ssl: true     # Default: true

# Enable caching (optional - default is enabled)
cache:
  enabled: true        # Default: true

# Basic logging (optional - defaults shown)
logging:
  level: info          # Default: info
  format: text         # Default: text

# MCP server configuration (required for MCP functionality)
mcp:
  enabled: true
  
  # Use stdio transport (no network configuration needed)
  server:
    transport: "stdio"
    
    # Database for MCP operations (optional - uses memory by default)
    database:
      url: "sqlite:./mcp-ratchet.db"  # Default: "sqlite::memory:"
  
  # No authentication for simplicity (default)
  authentication:
    method: "none"     # Default: "none"
  
  # Basic security settings (optional - these are defaults)
  security:
    rate_limiting:
      global_per_minute: 500           # Default
      execute_task_per_minute: 60      # Default
  
  # Enable core tools only (optional - these are defaults)
  tools:
    enable_execution: true             # Default: true
    enable_logging: true               # Default: true
    enable_monitoring: false           # Default: false
    enable_debugging: false            # Default: false
    enable_filesystem: false           # Default: false

# Basic task registry (required for task execution)
registry:
  sources:
    - name: "local-tasks"
      uri: "file://./sample/js-tasks"

# Output configuration (optional - defaults shown)
output:
  max_concurrent_deliveries: 10       # Default: 10
  default_timeout: 30                 # Default: 30 seconds
  validate_on_startup: true           # Default: true