# Test Configuration for Claude MCP Integration
execution:
  max_execution_duration: 180
  validate_schemas: true
  fetch_variables:
    url_var: "__fetch_url"
    params_var: "__fetch_params"
    body_var: "__fetch_body"
    result_var: "__http_result"
    temp_result_var: "__temp_result"

http:
  timeout: 30
  max_redirects: 5
  user_agent: "Ratchet-Claude-MCP/1.0"
  verify_ssl: true

cache:
  task_content_cache_size: 500
  enabled: true

logging:
  level: info
  format: json
  sinks:
    - type: console
      level: info
      use_json: false

# MCP Server Configuration
mcp:
  enabled: true
  server:
    transport: "stdio"
    database:
      url: "sqlite:./test-ratchet.db"
    
  authentication:
    method: "api_key"
    api_key:
      header_name: "Authorization"
      prefix: "Bearer"
      keys:
        "test-claude-client-key-12345":
          name: "Test Claude Desktop Client"
          description: "Test Claude Desktop application access"
          permissions:
            can_execute_tasks: true
            can_read_logs: true
            can_read_traces: false
            can_access_system_info: false
            allowed_task_patterns: ["*"]
            denied_task_patterns: ["system-*", "admin-*"]
          created_at: "2024-01-01T00:00:00Z"
          active: true
          allowed_ips: []

  security:
    rate_limiting:
      execute_task_per_minute: 60
      global_per_minute: 500

  tools:
    enable_execution: true
    enable_logging: true
    enable_monitoring: true
    enable_debugging: false
    enable_filesystem: false

# Task Registry
registry:
  sources:
    - name: "local-tasks"
      uri: "file://./sample/js-tasks"
      config:
        watch_for_changes: true
        auto_reload: false

# Output Configuration
output:
  max_concurrent_deliveries: 10
  default_timeout: 45
  validate_on_startup: true

# Server configuration for testing
server:
  bind_address: "127.0.0.1"
  port: 8080
  database:
    url: "sqlite:./test-ratchet.db"
    max_connections: 10
    connection_timeout: 30