# Test Configuration for Claude MCP Integration
# Optimized for testing with Claude Desktop

# Execution settings for testing
execution:
  max_execution_duration: 180         # Shorter timeout for testing
  validate_schemas: true              # Always validate in tests
  
  # Default fetch variables (optional)
  fetch_variables:
    url_var: "__fetch_url"
    params_var: "__fetch_params"
    body_var: "__fetch_body"
    result_var: "__http_result"
    temp_result_var: "__temp_result"

# HTTP configuration for external calls
http:
  timeout: 30                         # Default timeout
  max_redirects: 5                    # Conservative redirect limit
  user_agent: "Ratchet-Claude-MCP/1.0"  # Identify as test client
  verify_ssl: true                    # Always verify SSL in tests

# Enable caching for better performance
cache:
  enabled: true
  task_cache:
    task_content_cache_size: 500      # Larger cache for testing

# Structured logging for testing
logging:
  level: info                         # Info level for testing
  format: json                        # JSON format for parsing
  targets:
    - type: console
      level: info

# MCP Server Configuration for Claude integration
mcp:
  enabled: true
  
  server:
    transport: "stdio"                # Required for Claude Desktop
    
    # Test database (persisted for debugging)
    database:
      url: "sqlite:./test-ratchet.db"
  
  # API key authentication for testing
  authentication:
    method: "api_key"
    api_key:
      header_name: "Authorization"
      prefix: "Bearer"
      keys:
        "test-claude-client-key-12345":
          name: "Test Claude Desktop Client"
          description: "Test Claude Desktop application access"
          permissions:
            can_execute_tasks: true
            can_read_logs: true
            can_read_traces: false
            can_access_system_info: false
            allowed_task_patterns: ["*"]
            denied_task_patterns: ["system-*", "admin-*"]
          created_at: "2024-01-01T00:00:00Z"
          active: true
          allowed_ips: []              # No IP restrictions for testing

  # Relaxed security for testing
  security:
    rate_limiting:
      execute_task_per_minute: 60     # Allow more executions in tests
      global_per_minute: 500          # Higher global limit

  # Enable monitoring tools for testing
  tools:
    enable_execution: true
    enable_logging: true
    enable_monitoring: true           # Enable for debugging
    enable_debugging: false           # Keep debugging off for security
    enable_filesystem: false          # Disable filesystem access

# Task Registry for sample tasks
registry:
  sources:
    - name: "local-tasks"
      uri: "file://./sample/js-tasks"
      config:
        watch_for_changes: true       # Watch for changes during development
        auto_reload: false            # Manual reload for testing

# Output Configuration
output:
  max_concurrent_deliveries: 10
  default_timeout: 45                # Longer timeout for testing
  validate_on_startup: true

# Server configuration for testing
server:
  bind_address: "127.0.0.1"         # Localhost only for testing
  port: 8080                        # Default port
  
  database:
    url: "sqlite:./test-ratchet.db"  # Same database as MCP
    max_connections: 10
    connection_timeout: 30