name: Cache Dependencies

on:
  push:
    branches: [master]
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'ratchet-*/Cargo.toml'
  pull_request:
    paths:
      - 'Cargo.toml' 
      - 'Cargo.lock'
      - 'ratchet-*/Cargo.toml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  cache-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platform }}

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dependencies cache
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          target: builder
          push: false
          cache-from: |
            type=gha,scope=buildkit-deps-${{ matrix.platform }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-deps-${{ matrix.platform }}
          cache-to: |
            type=gha,scope=buildkit-deps-${{ matrix.platform }},mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-deps-${{ matrix.platform }},mode=max
          build-args: |
            CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            CARGO_INCREMENTAL=0

  # Notify the main workflow that dependencies are cached
  notify-cache-ready:
    runs-on: ubuntu-latest
    needs: cache-dependencies
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: dependencies-cached
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'