on:
  release:
    types: [created]

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:

          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          - os-name: Linux-riscv64
            runs-on: ubuntu-24.04
            target: riscv64gc-unknown-linux-gnu

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up dependencies (Ubuntu only)
        if: matrix.platform.runs-on == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config musl-dev
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        env:
          OPENSSL_STATIC: "1"
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release -p ratchet --features=vendored" # Try the 'vendored' feature
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ratchet
          target: ${{ matrix.platform.target }}
          changes-file: "CHANGES.md"
          archive-name: "ratchet-${{ github.event.release.tag_name }}-${{ matrix.platform.os-name }}"
