on:
  release:
    types: [created]

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: linux-x86_64
            runs-on: ubuntu-22.04
            target: x86_64-unknown-linux-musl

          - os-name: windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: macos-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up dependencies (Ubuntu only)
        if: matrix.platform.runs-on == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config musl-dev # Install musl-dev
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        env:
          OPENSSL_DIR: /usr
          OPENSSL_INCLUDE_DIR: /usr/include
          OPENSSL_LIB_DIR: /usr/lib/x86_64-linux-gnu # Adjust if necessary
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release -p ratchet"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ratchet
          target: ${{ matrix.platform.target }}
          changes-file: "CHANGES.md"
          archive-name: "ratchet-${{ github.event.release.tag_name }}-${{ matrix.platform.os-name }}"
